CREATE DATABASE CATAN_DB;

USE CATAN_DB;
	
CREATE TABLE Actv_Client (
    CLNT_NO INT PRIMARY KEY NOT NULL,
    CLNT_NAME VARCHAR(40) NOT NULL,
    CLNT_ADDR VARCHAR(50),
    CONTACTNO CHAR(11),  
    CLNT_COMPANY VARCHAR(50),
    CLNT_PROJ CHAR(6),
    CLNT_STATUS CHAR(1) NOT NULL
);

CREATE TABLE Psbl_Client (
    CLNT_NO INT PRIMARY KEY NOT NULL,
    CLNT_NAME VARCHAR(40) NOT NULL,
    CLNT_ADDR VARCHAR(50),
    CONTACTNO CHAR(11),  
    CLNT_COMPANY VARCHAR(50),
    CLNT_STATUS CHAR(1) NOT NULL
);

