USE CATAN_DB;

MERGE Actv_Client AS a
USING Psbl_Client AS p
	ON (a.CLNT_NO = p.CLNT_NO)
WHEN MATCHED THEN
	UPDATE SET a.CLNT_STATUS = p.CLNT_STATUS
WHEN NOT MATCHED BY TARGET THEN 
	INSERT (CLNT_NO, CLNT_NAME, CLNT_ADDR, CONTACTNO, CLNT_COMPANY, CLNT_STATUS) 
	VALUES (P.CLNT_NO, P.CLNT_NAME, P.CLNT_ADDR, P.CONTACTNO, P.CLNT_COMPANY, P.CLNT_STATUS)
WHEN NOT MATCHED BY SOURCE THEN 
	DELETE;